services:
  postgres:
    image: postgres:16-alpine
    container_name: customer-service-postgres
    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: customer_user
      POSTGRES_PASSWORD: customer_pass
    ports:
      - "5432:5432"
    volumes:
      - customer_pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  score-mock-service:
    build: ./score-mock-service
    container_name: score-mock-service
    ports:
      - "8081:8081"

  notification-service:
    build: ./notification-service
    container_name: notification-service
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq

  customer-service:
    build: ./customer-service
    container_name: customer-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SCORE_SERVICE_BASE_URL: http://score-mock-service:8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/customerdb
      SPRING_DATASOURCE_USERNAME: customer_user
      SPRING_DATASOURCE_PASSWORD: customer_pass
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - postgres
      - score-mock-service
      - rabbitmq

volumes:
  customer_pg_data: