version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: customer-service-postgres
    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: customer_user
      POSTGRES_PASSWORD: customer_pass
    ports:
      - "5432:5432"
    volumes:
      - customer_pg_data:/var/lib/postgresql/data

volumes:
  customer_pg_data: