spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/customerdb}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:customer_user}
    password: ${SPRING_DATASOURCE_PASSWORD:customer_pass}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect